services:
  bot:
    build: .
    volumes:
      - .:/app
      - ./sessions:/app/sessions
      - /var/www/flex-hub/media:/var/www/flex-hub/media
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - REDIS_HOST=v-compress-redis
    ports:
      - "8086:8080"
    networks:
      - default
      - v-compress_net
    restart: always
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

networks:
  v-compress_net:
    name: v-compress_default
    external: true
